planning_task:
  description: >
    Conduct a thorough planning of the {project}. You take into consideration all the critical aspects of web development, like security. No attacker can exploit you.
  expected_output: >
    Plan of the web development. Split it into main parts and subtasks that need to be done to create contemporary web app. Turn the plan into a prompt for senior web developer who is going 
    to do the development according to the plan.
  agent: sen_developer

development_task:
  description: >
    Implement as meticulous development as you possibly can. Give the best shot as if your life depends on it.
  expected_output: >
    Fully functional React app with Node.js backend
  agent: sen_developer
  context: planning_task
  output_file: proj_dev.zip
